name: Dispatch build to Jetstream cluster
on:
  workflow_dispatch: {}
jobs:
  jsbuild:
    env:
      NAMESPACE: js-build
      PVC: manual-js-build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          #token: ${{ secrets.PAT }}
          persist-credentials: true
      - name: save kubeconfig
        shell: bash
        run: mkdir -p ~/.kube && echo "${{ secrets.KUBECONFIG}}" > ~/.kube/config
      - shell: bash
        run: mkdir -p lists && mkdir -p logs && bash start_loop.sh -n $NAMESPACE -c $PVC -j packages.json -b lists/built -f lists/failed -l logs
        continue-on-error: true
      - shell: bash
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add .
          git commit -m "End of run"
          git push